version: 2

builds:
  - main: ./cmd/dfmicro
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz

signs:
  - cmd: cosign
    args:
      - sign-blob
      - --yes
      - --bundle=${signature}
      - ${artifact}
    artifacts: checksum

changelog:
  sort: asc
