apiVersion: config.openshift.io/v1
kind: Network
metadata:
  name: cluster
spec:
  clusterNetwork:
  - cidr: {{.ClusterCIDR}}
  serviceNetwork:
  - {{.ServiceCIDR}}
status:
  clusterNetwork:
  - cidr: {{.ClusterCIDR}}
  serviceNetwork:
  - {{.ServiceCIDR}}
  clusterNetworkMTU: 1500
