apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  monitoring:
    reconcileStrategy: ignore
  managedResources:
    cephObjectStores:
      reconcileStrategy: ignore
    cephObjectStoreUsers:
      reconcileStrategy: ignore
  multiCloudGateway:
    reconcileStrategy: ignore
  monPVCTemplate:
    spec:
      storageClassName: topolvm-provisioner-immediate
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
  placement:
    mon: {}
    mds: {}
    mgr: {}
    rbd-mirror: {}
    rgw: {}
    nfs: {}
    noobaa-core: {}
    noobaa-standalone: {}
    osd-prepare: {}
  resources:
    mon:
      requests:
        cpu: 125m
        memory: 128Mi
    mds:
      requests:
        cpu: 125m
        memory: 128Mi
    mgr:
      requests:
        cpu: 125m
        memory: 128Mi
    mgr-sidecar:
      requests:
        cpu: 125m
        memory: 128Mi
    nfs:
      requests:
        cpu: 125m
        memory: 128Mi
    noobaa-core:
      requests:
        cpu: 125m
        memory: 128Mi
    noobaa-db:
      requests:
        cpu: 125m
        memory: 128Mi
    noobaa-db-vol:
      requests:
        storage: 5Gi
    noobaa-endpoint:
      requests:
        cpu: 125m
        memory: 128Mi
    rbd-mirror:
      requests:
        cpu: 125m
        memory: 128Mi
    rgw:
      requests:
        cpu: 125m
        memory: 128Mi
  storageDeviceSets:
    - count: 1
      name: ocs-deviceset
      dataPVCTemplate:
        spec:
          storageClassName: topolvm-provisioner-immediate
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          volumeMode: Block
      placement: {}
      portable: false
      replica: 3
      resources:
        requests:
          cpu: 125m
          memory: 128Mi
