#!/usr/bin/env bash
set -euo pipefail

# Requires curl, helm, and yq. The generated assets are checked in so these
# tools are only needed when the chart version changes.

version="${TOPOLVM_VERSION:?TOPOLVM_VERSION is required}"
script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
assets_dir="${script_dir}/../internal/support/topolvm-assets"
template_file="${script_dir}/../internal/support/topolvm_gen.go"
marker="${assets_dir}/.topolvm-version"
chart_url="https://github.com/topolvm/topolvm/releases/download/topolvm-chart-v${version}/topolvm-${version}.tgz"

expected=(
	01-namespace.yaml
	02-topolvm.yaml
	kustomization.yaml
)
if [[ -f "${marker}" ]] && [[ "$(<"${marker}")" == "${version}" ]]; then
	ready=true
	for file in "${expected[@]}"; do
		if [[ ! -f "${assets_dir}/${file}" ]]; then
			ready=false
			break
		fi
	done
	if [[ "${ready}" == true ]] && [[ -f "${template_file}" ]]; then
		echo "TopoLVM ${version} manifests are up to date"
		exit 0
	fi
fi

missing=()
for dependency in curl helm yq; do
	if ! command -v "${dependency}" >/dev/null 2>&1; then
		missing+=("${dependency}")
	fi
done
if ((${#missing[@]} > 0)); then
	echo "error: missing required tools: ${missing[*]}" >&2
	exit 1
fi

tmp_dir="$(mktemp -d)"
trap 'rm -rf "${tmp_dir}"' EXIT
chart="${tmp_dir}/topolvm-${version}.tgz"
rendered="${tmp_dir}/assets"
mkdir -p "${rendered}"

curl -fsSL --retry 5 "${chart_url}" -o "${chart}"
helm template topolvm "${chart}" \
	--include-crds \
	--namespace=topolvm-system \
	--set cert-manager.enabled=false \
	--set webhook.podMutatingWebhook.enabled=false \
	--set webhook.caBundle=dummy \
	--set webhook.tlsSecretName=topolvm-webhook-cert \
	--set controller.replicaCount=1 \
	>"${rendered}/02-topolvm.yaml"

yq -i 'with(select(.kind == "StorageClass" and .metadata.name == "topolvm-provisioner"); .metadata.annotations."storageclass.kubernetes.io/is-default-class" = "true")' \
	"${rendered}/02-topolvm.yaml"

cat >"${rendered}/01-namespace.yaml" <<'EOF'
apiVersion: v1
kind: Namespace
metadata:
  name: topolvm-system
  labels:
    openshift.io/run-level: "0"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
EOF

yq -i 'del(.webhooks[].clientConfig.caBundle)' "${rendered}/02-topolvm.yaml"
yq 'select(.kind == "DaemonSet" and .metadata.name == "topolvm-lvmd-0") |
  .metadata.name = "topolvm-lvmd-{{.NodeName}}" |
  .metadata.labels."dfmicro.io/topolvm-node" = "{{.NodeName}}" |
  .spec.selector.matchLabels."dfmicro.io/topolvm-node" = "{{.NodeName}}" |
  .spec.template.metadata.labels."dfmicro.io/topolvm-node" = "{{.NodeName}}" |
  del(.spec.template.metadata.annotations."checksum/config") |
  .spec.template.spec.nodeSelector."kubernetes.io/hostname" = "{{.NodeName}}" |
	(.spec.template.spec.volumes[] | select(.name == "config").configMap.name) = "topolvm-lvmd-{{.NodeName}}"' \
	"${rendered}/02-topolvm.yaml" >"${rendered}/topolvm-lvmd-daemonset.yaml"
if [[ ! -s "${rendered}/topolvm-lvmd-daemonset.yaml" ]]; then
	echo "error: TopoLVM chart did not contain topolvm-lvmd-0 DaemonSet" >&2
	exit 1
fi
yq -i 'del(select(.kind == "ConfigMap" and .metadata.name == "topolvm-lvmd-0"))' \
	"${rendered}/02-topolvm.yaml"
yq -i 'del(select(.kind == "DaemonSet" and .metadata.name == "topolvm-lvmd-0"))' \
	"${rendered}/02-topolvm.yaml"
yq -i 'with(select(.kind == "Deployment" and .metadata.name == "topolvm-controller").spec.template.spec.containers[] | select(.name == "topolvm-controller"); .livenessProbe.failureThreshold = 3 | .readinessProbe.timeoutSeconds = 3 | .readinessProbe.failureThreshold = 3 | .readinessProbe.periodSeconds = 60 | .startupProbe = {"failureThreshold": 3, "periodSeconds": 60, "timeoutSeconds": 3, "httpGet": {"port": "healthz", "path": "/healthz"}})' \
	"${rendered}/02-topolvm.yaml"
yq -i 'with(select(.kind == "DaemonSet" and .metadata.name == "topolvm-node").spec.template.spec.containers[] | select(.name == "topolvm-node"); .startupProbe = {"failureThreshold": 60, "periodSeconds": 2, "timeoutSeconds": 3, "httpGet": {"port": "healthz", "path": "/healthz"}})' \
	"${rendered}/02-topolvm.yaml"
yq -i 'with(select(.kind == "DaemonSet" and .metadata.name == "topolvm-node").spec.template.spec;
  .initContainers = [{
    "name": "wait-for-lvmd",
    "image": (.containers[] | select(.name == "topolvm-node").image),
    "command": ["/bin/sh", "-c", "until [ -S /run/topolvm/lvmd.sock ]; do sleep 1; done"],
    "volumeMounts": [{"name": "lvmd-socket-dir", "mountPath": "/run/topolvm"}]
  }])' \
	"${rendered}/02-topolvm.yaml"
cat >"${rendered}/topolvm_gen.go" <<'EOF'
package support

// Code generated by hack/generate-topolvm.sh. DO NOT EDIT.
const topolvmLVMDTemplate = `---
apiVersion: v1
kind: ConfigMap
metadata:
  name: topolvm-lvmd-{{.NodeName}}
  namespace: topolvm-system
  labels:
    dfmicro.io/topolvm-node: "{{.NodeName}}"
data:
  lvmd.yaml: |
    socket-name: /run/topolvm/lvmd.sock
    device-classes:
      - name: ssd
        volume-group: {{.VGName}}
        default: true
        spare-gb: 1
{{- if .Thinpool}}
        type: thin
        thin-pool:
          name: thin
          overprovision-ratio: {{printf "%.1f" .OverprovisionRatio}}
{{- end}}
---
EOF
cat "${rendered}/topolvm-lvmd-daemonset.yaml" >>"${rendered}/topolvm_gen.go"
printf '%s\n' '`' >>"${rendered}/topolvm_gen.go"

cat >"${rendered}/kustomization.yaml" <<'EOF'
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 01-namespace.yaml
  - 02-topolvm.yaml
  - 03-dynamic.yaml
EOF

mkdir -p "${assets_dir}"
for file in "${expected[@]}"; do
	mv "${rendered}/${file}" "${assets_dir}/${file}"
done
mv "${rendered}/topolvm_gen.go" "${template_file}"
printf '%s\n' "${version}" >"${marker}"
echo "Generated TopoLVM ${version} manifests in ${assets_dir}"
